import orange from "../assets/orange.png";
import blue from "../assets/blue.png";
import green from "../assets/green.png";
import red from "../assets/red.png";

// Pre-generated by scripts/gen-images.mjs: encoding a PNG per request blows the free plan's 10ms CPU limit.
const PNGS = { orange, blue, green, red };

const getPng = (color) => PNGS[color] || PNGS.orange;

const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

function ogTags(origin, tag, color) {
  const img = `${origin}/img/${encodeURIComponent(tag)}.png?c=${color}`;
  return `
<meta property="og:type" content="website">
<meta property="og:site_name" content="OG Lab">
<meta property="og:url" content="${esc(`${origin}/p/${tag}`)}">
<meta property="og:title" content="OG Lab: ${esc(tag)}">
<meta property="og:description" content="Test card for ${esc(tag)} (color ${esc(color)})">
<meta property="og:image" content="${esc(img)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">`;
}

const page = ({ title, head = "", body = "" }) =>
  `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>${head}</head><body>${body}</body></html>`;

function log(request, route, extra = {}) {
  const h = request.headers;
  const cf = request.cf || {};
  console.log(
    JSON.stringify({
      t: new Date().toISOString(),
      method: request.method,
      url: request.url,
      route,
      ip: h.get("cf-connecting-ip"),
      ua: h.get("user-agent"),
      asn: cf.asn,
      asOrg: cf.asOrganization,
      country: cf.country,
      city: cf.city,
      colo: cf.colo,
      accept: h.get("accept"),
      acceptLanguage: h.get("accept-language"),
      range: h.get("range"),
      referer: h.get("referer"),
      secFetchMode: h.get("sec-fetch-mode"),
      ...extra,
    }),
  );
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const origin = url.origin;
    const parts = url.pathname.split("/").filter(Boolean);
    const color = url.searchParams.get("c") || "orange";
    const isHead = request.method === "HEAD";
    const html = (status, body) =>
      new Response(isHead ? null : body, {
        status,
        headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" },
      });

    if (url.pathname === "/favicon.ico") {
      log(request, "favicon");
      return new Response(null, { status: 404 });
    }

    // Static OG tags in the HTML.
    if (parts[0] === "p" && parts[1]) {
      const tag = decodeURIComponent(parts[1]);
      log(request, "page", { tag });
      return html(200, page({ title: `OG Lab: ${tag}`, head: ogTags(origin, tag, color), body: `<h1>OG Lab: ${esc(tag)}</h1>` }));
    }

    // OG tags only injected by JS; a beacon fires if the fetcher executes JS.
    if (parts[0] === "js" && parts[1]) {
      const tag = decodeURIComponent(parts[1]);
      log(request, "js-page", { tag });
      const script = `
<script>
  document.head.insertAdjacentHTML("beforeend", ${JSON.stringify(ogTags(origin, tag, "green"))});
  document.title = ${JSON.stringify(`OG Lab JS: ${tag}`)};
  fetch("/beacon/${encodeURIComponent(tag)}?ua=" + encodeURIComponent(navigator.userAgent));
</script>`;
      return html(200, page({ title: "Loading…", head: script, body: "<h1>JS-only OG</h1>" }));
    }

    if (parts[0] === "beacon") {
      log(request, "BEACON", { tag: parts[1] });
      return new Response(null, { status: 204 });
    }

    if (parts[0] === "r" && parts[1]) {
      log(request, "redirect", { tag: parts[1] });
      return Response.redirect(`${origin}/p/${parts[1]}${url.search}`, 302);
    }

    if (parts[0] === "slow" && parts[1]) {
      const ms = Math.min(Number(url.searchParams.get("ms") || 10000), 25000);
      log(request, "slow", { tag: parts[1], ms });
      await new Promise((r) => setTimeout(r, ms));
      return html(200, page({ title: `slow ${parts[1]}`, head: ogTags(origin, `slow-${parts[1]}`, "red") }));
    }

    if (parts[0] === "img") {
      const png = getPng(color);
      log(request, "image", { color, bytes: png.byteLength });
      return new Response(isHead ? null : png, {
        headers: { "content-type": "image/png", "content-length": String(png.byteLength), "cache-control": "no-store" },
      });
    }

    log(request, "other");
    return html(404, page({ title: "404", body: "not found" }));
  },
};
