import { Hono } from "hono";
import orange from "../assets/orange.png";
import blue from "../assets/blue.png";
import green from "../assets/green.png";
import red from "../assets/red.png";

// Pre-generated by scripts/gen-images.js: encoding a PNG per request blows the free plan's 10ms CPU limit.
const PNGS = { orange, blue, green, red };

const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

// og:url must keep the query string: Facebook re-scrapes the og:url as the canonical page.
function ogTags(origin, tag, color, cache = false, pageUrl = `${origin}/p/${tag}`) {
  const img = `${origin}/img/${encodeURIComponent(tag)}.png?c=${color}${cache ? "&cache=1" : ""}`;
  return `
<meta property="og:type" content="website">
<meta property="og:site_name" content="OG Lab">
<meta property="og:url" content="${esc(pageUrl)}">
<meta property="og:title" content="OG Lab: ${esc(tag)}">
<meta property="og:description" content="Test card for ${esc(tag)} (color ${esc(color)})">
<meta property="og:image" content="${esc(img)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">`;
}

const page = ({ title, head = "", body = "" }) =>
  `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>${head}</head><body>${body}</body></html>`;

const app = new Hono();

// Every request is logged once, after the handler has labelled it via c.set("route", ...).
app.use("*", async (c, next) => {
  const t = new Date().toISOString();
  const url = new URL(c.req.url);
  const cache = url.searchParams.get("cache") === "1";
  c.set("origin", url.origin);
  c.set("color", url.searchParams.get("c") || "orange");
  c.set("cache", cache);
  // ?cache=1 mimics a typical static host (jamesisme.com on GitHub Pages sends max-age=600).
  c.set("cacheControl", cache ? "public, max-age=600" : "no-store");

  await next();

  const cf = c.req.raw.cf || {};
  console.log(
    JSON.stringify({
      t,
      method: c.req.method,
      url: c.req.url,
      route: c.get("route") || "other",
      status: c.res.status,
      ip: c.req.header("cf-connecting-ip"),
      ua: c.req.header("user-agent"),
      asn: cf.asn,
      asOrg: cf.asOrganization,
      country: cf.country,
      city: cf.city,
      colo: cf.colo,
      accept: c.req.header("accept"),
      acceptLanguage: c.req.header("accept-language"),
      range: c.req.header("range"),
      referer: c.req.header("referer"),
      secFetchMode: c.req.header("sec-fetch-mode"),
      origin: c.req.header("origin"),
      ...c.get("extra"),
    }),
  );
});

const html = (c, body, status = 200) => {
  c.header("cache-control", c.get("cacheControl"));
  return c.html(body, status);
};

const tagged = (c, route) => {
  const tag = c.req.param("tag");
  c.set("route", route);
  c.set("extra", { tag, cache: c.get("cache") });
  return tag;
};

// Static OG tags in the HTML.
app.get("/p/:tag", (c) => {
  const tag = tagged(c, "page");
  const head = ogTags(c.get("origin"), tag, c.get("color"), c.get("cache"), c.req.url);
  return html(c, page({ title: `OG Lab: ${tag}`, head, body: `<h1>OG Lab: ${esc(tag)}</h1>` }));
});

// Same as /p but readable cross-origin, to test whether in-browser preview builders are blocked by CORS.
app.get("/cors/:tag", (c) => {
  const tag = tagged(c, "cors");
  c.header("access-control-allow-origin", "*");
  const head = ogTags(c.get("origin"), tag, "blue", c.get("cache"), c.req.url);
  return html(c, page({ title: `OG Lab: ${tag}`, head, body: `<h1>OG Lab: ${esc(tag)}</h1>` }));
});

// OG tags only injected by JS; a beacon fires if the fetcher executes JS.
app.get("/js/:tag", (c) => {
  const tag = tagged(c, "js-page");
  const script = `
<script>
  document.head.insertAdjacentHTML("beforeend", ${JSON.stringify(ogTags(c.get("origin"), tag, "green"))});
  document.title = ${JSON.stringify(`OG Lab JS: ${tag}`)};
  fetch("/beacon/${encodeURIComponent(tag)}?ua=" + encodeURIComponent(navigator.userAgent));
</script>`;
  return html(c, page({ title: "Loading…", head: script, body: "<h1>JS-only OG</h1>" }));
});

app.get("/beacon/:tag", (c) => {
  tagged(c, "BEACON");
  return c.body(null, 204);
});

app.get("/r/:tag", (c) => {
  const tag = tagged(c, "redirect");
  const { search } = new URL(c.req.url);
  return c.redirect(`${c.get("origin")}/p/${encodeURIComponent(tag)}${search}`, 302);
});

app.get("/slow/:tag", async (c) => {
  const tag = tagged(c, "slow");
  const ms = Math.min(Number(c.req.query("ms") || 10000), 25000);
  c.set("extra", { ...c.get("extra"), ms });
  await new Promise((r) => setTimeout(r, ms));
  return html(c, page({ title: `slow ${tag}`, head: ogTags(c.get("origin"), `slow-${tag}`, "red") }));
});

app.get("/img/:file", (c) => {
  const color = c.get("color");
  const png = PNGS[color] || PNGS.orange;
  c.set("route", "image");
  c.set("extra", { color, cache: c.get("cache"), bytes: png.byteLength });
  return c.body(png, 200, {
    "content-type": "image/png",
    "content-length": String(png.byteLength),
    "cache-control": c.get("cacheControl"),
    "access-control-allow-origin": "*",
  });
});

app.get("/favicon.ico", (c) => {
  c.set("route", "favicon");
  return c.body(null, 404);
});

app.notFound((c) => html(c, page({ title: "404", body: "not found" }), 404));

export default app;
